### ISSUE TITLE
Train Chinese

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-models#14]
zh-CN (Chinese simplified) is meant here

**Comment by Riajyuu** [comment]
Just a question here: Chinese is graphic language which is completely different logic from letter language used in Europe & American. But, by checking model data, all training logic seems optimized for only letter processing.

**Comment by marco-c** [comment]
We are tracking requests for new languages on https://connect.mozilla.org/ (for example, https://connect.mozilla.org/t5/ideas/support-chinese-translations/idi-p/33405).
