### ISSUE TITLE
Train Japanese

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-models#15]

**Comment by onokatio** [comment]
@eu9ene Any update? How can I contribute?

**Comment by marco-c** [comment]
We are tracking requests for new languages on https://connect.mozilla.org/ (for example, https://connect.mozilla.org/t5/ideas/japanese-translate-option-in-firefox-translations/idi-p/22959).

@onokatio if you are still interested in contributing, let us know.
