### ISSUE TITLE
Use trained model on offline computer 

### ISSUE THREAD

**Issue by FredrikJoh** [mozilla/firefox-translations-models#172]
What is the process for taking a trained model from this repo and using it with Firefox on a stand-alone computer? 

After instaliing Firefox on the offline stand-alone computer, where do I save the models so that Firefox Translate can find and use them for translation? If possible, I would like to know the answer for both Linux and Windows.

Thanks for a great work!

**Comment by gregtatum** [comment]
You can use Firefox Translations in the browser with offline support via `about:preferences`.

<img width="687" alt="Screenshot of Firefox Translations in about:preferenes" src="https://github.com/user-attachments/assets/ca8501c1-80e3-4fb1-9e56-7ac283b18afe">

It sounds like you are trying to have pre-loaded models. In this case you would probably have to copy over a user profile directory, as they are stored there inside of SQLite via RemoteSettings. So there's no simple file location.
