### ISSUE TITLE
Add French

### ISSUE THREAD

**Issue by eu9ene** [mozilla/firefox-translations-models#18]
It will be trained by the Bergamot consortium.

**Comment by Utopiah** [comment]
Any estimated timeline?

**Comment by andrenatal** [comment]
@kpu is the only one able to provide an estimate

**Comment by kpu** [comment]
Happening this month.  I was trading messages about the data cleaning today.  Apparently something was also causing misalignment in the cleaning part of the snakemake pipeline so we're back to raw mtdata.

**Comment by sylvestre** [comment]
Merci beaucoup!
