### ISSUE TITLE
Swedish

### ISSUE THREAD

**Issue by lerra** [mozilla/firefox-translations-models#47]
Hi,

I would like to start with a big thanks for a privacy focused translation add-on! 

From my perspective I would like to see Swedish as a model, hopefully there is some pre-trained modules out there that could be used :)

**Comment by eu9ene** [comment]
I can run it, there is plenty of parallel data but there is no monolingual NewsCrawl data on https://data.statmt.org/news-crawl/ which we usually use for augmentation. @XapaJIaMnu maybe you can suggest what would be a good replacement?

**Comment by kpu** [comment]
Swedish hasn't been a WMT news task language (though apparently it was a biomedical language in 2017).  Time to whip out https://github.com/bitextor/monocleaner/ ?  
Also, https://blogs.helsinki.fi/fiskmo-project/resources/ but it seems to be web anyway.

**Comment by marco-c** [comment]
We are tracking requests for new languages on https://connect.mozilla.org/ (for example, https://connect.mozilla.org/t5/ideas/japanese-translate-option-in-firefox-translations/idi-p/22959).
