### ISSUE TITLE
Recipies for reproducing models

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/firefox-translations-models#58]
Is there a place where the recipes for reproducing the models in this repo live? I wasn't able to find anything here or at https://github.com/mozilla/firefox-translations-training

**Comment by eu9ene** [comment]
Here is an example of a production training recipe: https://github.com/mozilla/firefox-translations-training/blob/main/configs/config.prod.yml. We do not distribute configs of the trained models but they would be similar to this one. Available open source datasets are constantly changing, some parameters are hardware-dependent and there are just random experimentation bets like playing with early-stopping, so I don't think those configs would be particularly useful.

**Comment by marco-c** [comment]
Things are changing now with the new pipeline based on Taskcluster: https://github.com/mozilla/firefox-translations-training.
The configurations will be visible both in Taskcluster and in Weights & Biases.
