### ISSUE TITLE
Add Lithuanian models

### ISSUE THREAD

**Issue by justinasbardauskas** [mozilla/firefox-translations-models#61]
Hi, 
I'm very interested in this project and I would like to see Lithuanian (LT) language models in this project.  I did some fast checking:

- https://www.statmt.org/wmt19/translation-task.html#download  - in wmt19 LT was a news task language
- https://data.statmt.org/news-crawl/lt/ - LT monolingual NewsCrawl data 
- https://paracrawl.eu/ - contains LT datasets 
- https://opus.nlpl.eu/ - contains LT datasets

Looks like there is substantial amount of data, though I'm not sure if that is sufficient to train models, but I hope it is. 

Thanks :)

**Comment by marco-c** [comment]
We are tracking requests for new languages on https://connect.mozilla.org/ (for example, https://connect.mozilla.org/t5/ideas/japanese-translate-option-in-firefox-translations/idi-p/22959).

On another note, if you are interested in contributing, let us know.
