### ISSUE TITLE
Remove the distinction between prod and dev

### ISSUE THREAD

**Issue by marco-c** [mozilla/firefox-translations-models#69]
It has good quality according to COMET.

**Comment by eu9ene** [comment]
It seems like we're not deciding what models to ship in Firefox based on the prod/dev labels in this repo. As soon as we retire the web extension, we can just merge them all together.

**Comment by marco-c** [comment]
Agreed, we should simplify things and move everything into a single folder

**Comment by eu9ene** [comment]
Actually, we discussed this with @nordzilla and decided that prod and dev should correspond to Release and Nightly channels. It will be an indicator for the automatic uploading to the Remote settings where to add the Nightly filter. See this PR https://github.com/mozilla/firefox-translations-models/pull/83. So, I'm closing this for now, until we decide to structure it differently.
